[project]
authors = ["Tassos Manganaris <tassos.manganaris@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "decision-transformer"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.8,<3.12"

[pypi-dependencies]
corallab-policies = { path = ".", editable = true }
corallab-lib = { git = "https://github.com/Tass0sm/corallab-lib.git", tag = "v0.2.1" }
matplotlib = ">=3.9.2, <4"
tqdm = ">=4.66.5, <5"
decision-transformer = { path = "/home/tassos/phd/research/second-project/decision-transformer", editable = true }
gym = ">=0.23, <0.24"
d4rl = ">=1.1, <2"
cython = "<3"
mjrl = { path = "/home/tassos/phd/research/mjrl" }
torch = ">=2.4.1, <3"
wandb = ">=0.18.2, <0.19"
transformers = ">=4.45.1, <5"

[environments]
default = { solve-group = "default" }
